// ── Devicon icon map ──────────────────────────────────────────────────────────
export const TECH_ICONS: Record<string, string> = {
  'Next.js':       'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg',
  'TypeScript':    'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg',
  'JavaScript':    'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg',
  'React':         'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg',
  'PHP':           'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-original.svg',
  'Go':            'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/go/go-original-wordmark.svg',
  'Python':        'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg',
  'Ethereum':      'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/ethereum.svg',
  'HTMX':          'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/htmx.svg',
  'PostgreSQL':    'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg',
  'MySQL':         'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg',
  'Docker':        'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg',
  'Node.js':       'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg',
  'CSS3':          'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg',
  'HTML5':         'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg',
  'Git':           'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg',
  'Linux':         'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg',
  'Three.js':      'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/threejs/threejs-original.svg',
  'Tailwind':      'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg',
  'npm':           'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/npm/npm-original-wordmark.svg',
  'CLI':           'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bash/bash-original.svg',
  'GSAP':          'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg',
  'WebGL':         'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/webgl.svg',
  'Framer Motion': 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/framer.svg',
  'SQLite':        'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sqlite/sqlite-original.svg',
};

export const STACK = ['Next.js', 'TypeScript', 'PHP', 'Python', 'PostgreSQL', 'MySQL', 'Go', 'Node.js', 'Git'];

// ── Terminal lines ────────────────────────────────────────────────────────────
export const TERMINAL_LINES = [
  { delay: 0,    text: '$ phantomit watch --on-save', type: 'cmd' },
  { delay: 700,  text: 'watching: src/', type: 'dim' },
  { delay: 1400, text: '[11:42 PM] ✎ src/auth.ts, ✚ src/middleware.ts', type: 'dim' },
  { delay: 2400, text: 'generating commit message...', type: 'thinking' },
  { delay: 3800, text: '✦ Commit message:', type: 'label' },
  { delay: 4200, text: '"feat(auth): add JWT validation middleware"', type: 'message' },
  { delay: 4900, text: '[Y] commit & push   [E] edit   [N] skip', type: 'dim' },
  { delay: 5500, text: '→ y', type: 'cmd' },
  { delay: 6000, text: '✔ committed & pushed to origin/main', type: 'success' },
];

export const PHANTOMCRAWL_LINES = [
  { delay: 0,    text: '$ phantomcrawl start', type: 'cmd' },
  { delay: 600,  text: 'Loading crawl.json...', type: 'dim' },
  { delay: 1000, text: '✓ 1 URLs found', type: 'success' },
  { delay: 1400, text: '✓ Browserless client initialized.', type: 'success' },
  { delay: 1900, text: 'Batch 1/1', type: 'label' },
  { delay: 2300, text: '  crawling https://cloudflare.com ...', type: 'dim' },
  { delay: 3200, text: '  ✓ (layer1) https://cloudflare.com', type: 'success' },
  { delay: 3700, text: '  ✓ (layer1) https://cloudflare.com/en-gb', type: 'success' },
  { delay: 4100, text: '  ✓ (layer1) https://cloudflare.com/de-de', type: 'success' },
  { delay: 4500, text: '  ✓ (layer1) https://cloudflare.com/es-la', type: 'success' },
  { delay: 5100, text: '  cleaned https://cloudflare.com', type: 'thinking' },
  { delay: 6000, text: '✓ AI cleaning complete.', type: 'success' },
  { delay: 6600, text: 'Total crawled : 4   Failed : 0', type: 'label' },
  { delay: 7100, text: 'Output : ~/phantomcrawl/scraped', type: 'dim' },
];

// ── Projects ──────────────────────────────────────────────────────────────────
export const PROJECTS = [
  {
    title: 'PhantomCrawl',
    desc: 'Most scrapers get blocked the moment they hit a protected site. PhantomCrawl does not. It uses a 4-layer escalation engine: TLS fingerprinting that mimics Chrome at the handshake level, network hijacking to extract embedded JSON before the page even renders, XHR/fetch interception to capture live API responses, and headless browser fallback via go-rod or Browserless. It scraped Cloudflare.com — a site protected by Cloudflare itself — across 100+ pages at depth 1, zero blocks, all Layer 1. Includes AI cleaning via Groq or OpenAI, proxy rotation tunneled through the TLS transport, SQLite state tracking with full resume, and cross-platform binaries for Linux, Mac, and Windows. No runtime required.',
    visual: 'phantomcrawl' as const,
    images: [] as string[],
    live: 'https://phantomcrawl.vercel.app',
    github: 'https://github.com/var-raphael/PhantomCrawl',
    closedSource: false,
    proof: 'https://github.com/var-raphael/PhantomCrawl/tree/main/scraped_data_real_samples',
    tags: ['Go', 'SQLite', 'CLI'],
  },
  {
    title: 'phantomit',
    desc: 'Tired of writing lazy git commit messages like "fix stuff" or forgetting to push entirely? phantomit watches your code, diffs every change, and generates a meaningful commit message automatically via Groq AI. One command replaces the part of your workflow you keep procrastinating on. Published on npm, works with any Node.js project.',
    visual: 'terminal' as const,
    images: [] as string[],
    live: 'https://phantomit-docs.vercel.app',
    github: 'https://github.com/var-raphael/phantomit',
    closedSource: false,
    tags: ['Node.js', 'TypeScript', 'CLI', 'npm'],
  },
  {
    title: 'PhantomTrack',
    desc: 'Google Analytics is a cockpit when you need a light switch. Fathom and Plausible cost $14/month before you have a single paying user. PhantomTrack gives you everything that matters: visitors, pages, clicks, session duration, referrers. All on one scrollable page, no cookies, no data sold, no noise. One script tag. Works on any site including React and Next.js SPAs. 10+ active users including developers from the US.',
    visual: 'img' as const,
    images: ['/portfolio-images/img/phantomtrack1.jpg', '/portfolio-images/img/phantomtrack2.jpg'],
    live: 'https://phantomtrack-docs.vercel.app',
    github: '',
    closedSource: true,
    tags: ['PHP', 'MySQL'],
  },
  {
    title: 'ClassFlow',
    desc: 'Managing assignments over WhatsApp and email is chaos for both teachers and students. ClassFlow replaces that with a clean platform where teachers post assignments, students submit work, and grading happens in one place. Real-time grading, file uploads, threaded comments, and dashboards that show who submitted and who did not. Built for schools that cannot afford expensive tools.',
    visual: 'img' as const,
    images: ['/portfolio-images/img/classflow1.jpg', '/portfolio-images/img/classflow2.jpg'],
    live: 'https://myclassflow.vercel.app',
    github: 'https://github.com/var-raphael/classflow',
    closedSource: false,
    tags: ['Next.js', 'TypeScript', 'PostgreSQL'],
  },
  {
    title: 'NaijaStock',
    desc: 'A Nigerian stock market platform for purchasing and exchanging stocks built for the local market. Real-time trading, portfolio tracking, and blockchain-backed transactions via Ethereum. Designed to make Nigerian equities accessible to everyday investors without the friction of traditional brokers.',
    visual: 'img' as const,
    images: ['/portfolio-images/img/stockvel1.jpg', '/portfolio-images/img/stockvel2.jpg'],
    live: '#',
    github: 'https://github.com/var-raphael/nigeria-stock',
    closedSource: false,
    wip: true,
    tags: ['Next.js', 'TypeScript', 'PostgreSQL', 'Ethereum'],
  },
  {
    title: 'PhantomScrape',
    desc: 'Most scraping tools are either too heavy to self-host or charge per request. PhantomScrape lets you bulk-scrape any list of URLs, clean the raw HTML into structured data using Groq AI, and export results in JSON, CSV, XML, HTML, or TXT. Live status tracking per URL, keyless auth, and a clean dashboard. Flask backend on Render, Next.js frontend on Vercel, Supabase for storage.',
    visual: 'img' as const,
    images: ['/portfolio-images/img/phantomscrape1.jpg', '/portfolio-images/img/phantomscrape2.jpg'],
    live: 'https://phantomscrape.vercel.app',
    github: 'https://github.com/var-raphael/phantomscrape-frontend',
    closedSource: false,
    wip: false,
    tags: ['Python', 'Next.js', 'TypeScript', 'PostgreSQL'],
  },
  {
    title: 'PhantomNotes',
    desc: 'Uploading a 40-page PDF to get a wall of text back is not useful. PhantomNotes lets you choose how you want your document summarized: student study notes, business action items, legal clause extraction, research methodology, meeting decisions, and more. Ten specialized summary types, PDF and text input, multiple export formats, and documents are never stored permanently.',
    visual: 'img' as const,
    images: ['/portfolio-images/img/phantomnotes1.jpg', '/portfolio-images/img/phantomnotes2.jpg'],
    live: 'https://phantom-notes.onrender.com',
    github: 'https://github.com/var-raphael/phantomNotes',
    closedSource: false,
    tags: ['Python', 'HTMX', 'JavaScript', 'CSS3'],
  },
  {
    title: 'Go Rate Limiter',
    desc: 'Most rate limiting middleware adds overhead you cannot afford at scale. This library is built in Go from the ground up for raw performance: token bucket and sliding window algorithms, tested against DDoS traffic patterns, handles 10k+ requests per second without breaking a sweat. Drop it into any Go service and your API is protected in minutes. No external dependencies.',
    visual: 'img' as const,
    images: ['/portfolio-images/img/rate1.jpg', '/portfolio-images/img/rate2.jpg'],
    live: '#',
    github: 'https://github.com/var-raphael/Ratelimiter',
    closedSource: false,
    tags: ['Go'],
  },
];

// ── Jewelry Collections ───────────────────────────────────────────────────────
export const JEWELRY_COLLECTIONS = [
  {
    name: 'Aqua Collection',
    desc: 'Cool-toned jewelry store with a crisp aqua palette. Showcases rings and accessories in an airy, modern layout with smooth hover transitions and a streamlined checkout experience.',
    images: ['/portfolio-images/img/ecomm-aqua1.jpg', '/portfolio-images/img/ecomm-aqua2.jpg'],
    live: 'https://phantom-demos.vercel.app/jewelry-teal',
    tags: ['Next.js', 'TypeScript', 'Tailwind', 'Framer Motion'],
  },
  {
    name: 'Coal Collection',
    desc: 'Bold, dark-mode e-commerce experience built for high-end prestige jewelry. Deep charcoal tones, dramatic product lighting, and an editorial grid that commands attention.',
    images: ['/portfolio-images/img/ecomm-coal1.jpg', '/portfolio-images/img/ecomm-coal2.jpg'],
    live: 'https://phantom-demos.vercel.app/watch-coal',
    tags: ['Next.js', 'TypeScript', 'Tailwind', 'Framer Motion'],
  },
  {
    name: 'Floral Collection',
    desc: 'Nature-inspired jewelry storefront with warm, organic aesthetics. Floral motifs woven into the layout guide customers through curated collections with an elegant, botanical feel.',
    images: ['/portfolio-images/img/ecomm-flw1.jpg', '/portfolio-images/img/ecomm-flw2.jpg'],
    live: 'https://phantom-demos.vercel.app',
    tags: ['Next.js', 'TypeScript', 'Tailwind', 'Framer Motion'],
  },
  {
    name: 'Ice Collection',
    desc: 'Glacial, ultra-clean jewelry landing page inspired by diamonds and frost. Minimal white space, sharp typography, and a sleek product showcase built to highlight icy, brilliant pieces.',
    images: ['/portfolio-images/img/ecomm-ice1.jpg', '/portfolio-images/img/ecomm-ice2.jpg'],
    live: 'https://phantom-demos.vercel.app/iced',
    tags: ['Next.js', 'TypeScript', 'Tailwind', 'Framer Motion'],
  },
];
